version: 2
jobs:
  build:
    docker:
      # name of root build image
      - image: circleci/python:3.6.1
    working_directory: ~/device-tracking
    environment:
      - TERRAFORM_VERSION: 0.11.1
      - TERRAFORM_PROJECT: "device-tracking"
      - ECR_REPOSITORY_NAME: "docker-hello-world"
      - DEVOPS_CI_VERSION: "1.0.48"
    steps:
      # checkout the files from github
      - checkout
      - run:
          name: Install Ruby dependencies
          command: sudo pip install \ docker-compose==1.12.0 \ awscli==1.11.76
  deploy:
- run:
  name: Build device-tracker
  command: mvn clean build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
